function figure1 = make_speedup_threads_chart(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Jul-2015 13:39:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorGrid','on','YGrid','on',...
    'XMinorGrid','on',...
    'XGrid','on',...
    'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
    'YMinorTick','on',...
    'XMinorTick','on',...
    'XColor',[0 0 0],...
    'FontSize',24,...
    'YLim', [0 1.1*max(YMatrix1(:))],...
    'AmbientLightColor',[0.8 0.8 0.8]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Achieved Speedup','FontSize',30);

% Create xlabel
xlabel('Number of threads','FontSize',30);

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'LineWidth',2.5,'Parent',axes1);

