function createfigure(X1, YMatrix1, yaxislabel)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Aug-2015 17:45:03

% Create figure
figure1 = figure;

% Create axes
% Create axes
axes1 = axes('Parent',figure1,'YMinorGrid','on','YGrid','on',...
    'XMinorGrid','on',...
    'XGrid','on',...
    'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
    'YMinorTick','on',...
    'XMinorTick','on',...
    'FontSize',24,...
    'XLim', [0 120],...
    'AmbientLightColor',[0.466666666666667 0.674509803921569 0.188235294117647]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel(yaxislabel,'FontSize',30);

% Create xlabel
xlabel('Network width','FontSize',30);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth', 2);

set(plot1(1),'DisplayName','8 CPUs','Color',[0 0.447 0.741]);
set(plot1(2),'DisplayName','18 CPUs','Color',[0.85 0.325 0.098]);
set(plot1(3),'DisplayName','40 CPUs','Color',[0.929 0.694 0.125]);
set(plot1(4),'DisplayName','60 CPUs','Color',[0.494 0.184 0.556]);
set(plot1(5),'DisplayName','120 CPUs','Color',[0.466 0.674 0.188]);

for id = 1:(size(YMatrix1,2)/5-1)
    set(plot1(id*5+1),'Color',[0 0.447 0.741]);
    set(plot1(id*5+2),'Color',[0.85 0.325 0.098]);
    set(plot1(id*5+3),'Color',[0.929 0.694 0.125]);
    set(plot1(id*5+4),'Color',[0.494 0.184 0.556]);
    set(plot1(id*5+5),'Color',[0.466 0.674 0.188]);
end;
% Create legend
legend1 = legend(axes1,'show',plot1(1:5), {'8 CPUs','18 CPUs','40 CPUs','60 CPUs','120 CPUs'});
set(legend1,'Color',[1 1 1],'FontSize', 20, 'EdgeColor', [1 1 1]);

