function [ r ] = append_cost( a, b )

    r = struct( 'flops' , a.flops + b.flops, ...
                'memory', max(a.memory, b.memory), ...
                'stack' , max(a.stack, b.stack), ...
                'stored', a.stored + b.stored);

end
