function makeplot(X1, YMatrix1,ylab)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Jun-2015 01:23:21

% Create figure
figure1 = figure('Position', [100, 100, 680, 435]);

% Create axes
axes1 = axes('Parent',figure1,'YMinorGrid','on','YGrid','on',...
    'XMinorGrid','on',...
    'XGrid','on',...
    'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
    'YMinorTick','on',...
    'XMinorTick','on',...
    'FontSize',18,...
    'AmbientLightColor',[0.466666666666667 0.674509803921569 0.188235294117647]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel(ylab, 'FontSize', 20);

% Create xlabel
xlabel('Network width', 'FontSize', 20);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2.5,'Parent',axes1);
set(plot1(1),'DisplayName','8 Core Intel Xeon E5-2666','Marker','^');
set(plot1(2),'DisplayName','18 Core Intel Xeon E5-2666','Marker','+');
set(plot1(3),'DisplayName','40 Core Intel Xeon i7-5820K','Marker','square');
set(plot1(4),'DisplayName','Intel Xeon Phi 5110P','Marker','x');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.731811697574893 0.737193763919822 0.158345221112696 0.164810690423162],...
    'Color',[1 1 1],'FontSize',18);

